dagen = ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag', 'Zondag']
print('Alle dagen van de week zijn:')
print(dagen)
print('De werkdagen zijn:')
print(dagen[0:5])
print('De weekenddagen zijn:')
print(dagen[5:])
print('De werkdagen in omgekeerde volgorde zijn:')
dagen.reverse()
print(dagen)
print('De weekenddagen in omgekeerde volgorde zijn:')
print(dagen[0:2])
dagen.reverse()